export const EMOTES = [
  { id: "bounce", label: "Bounce", icon: "🦘", ms: 3200, pose: "happy" },
  { id: "spin", label: "Spin", icon: "🌀", ms: 1200, pose: "happy" },
  { id: "wiggle", label: "Wiggle", icon: "💃", ms: 3500, pose: "happy" },
  { id: "pump", label: "Pump", icon: "🙌", ms: 3500, pose: "happy" },
  { id: "shuffle", label: "Shuffle", icon: "🕺", ms: 4000, pose: "happy" },
  { id: "sway", label: "Hip Sway", icon: "😏", ms: 4800, pose: "neutral" },
  { id: "shimmy", label: "Shimmy", icon: "✨", ms: 2400, pose: "neutral" },
  { id: "bodyroll", label: "Body Roll", icon: "🌊", ms: 4800, pose: "neutral" },
  { id: "strut", label: "Catwalk", icon: "😎", ms: 3200, pose: "neutral" },
  { id: "dip", label: "The Dip", icon: "🔥", ms: 4800, pose: "neutral" },
  { id: "litefeet", label: "Litefeet", icon: "👟", ms: 3200, pose: "neutral" },
  {
    id: "breakdance",
    label: "Breakdance",
    icon: "🤸",
    ms: 3200,
    pose: "neutral",
  },
  { id: "robot", label: "Robot", icon: "🤖", ms: 3200, pose: "neutral" },
  { id: "krump", label: "Krump", icon: "💢", ms: 3200, pose: "angry" },
  { id: "dancehall", label: "Dancehall", icon: "🌴", ms: 4800, pose: "happy" },
  { id: "ballet", label: "Ballet", icon: "🩰", ms: 4800, pose: "neutral" },
  { id: "locking", label: "Locking", icon: "🔒", ms: 4800, pose: "neutral" },
] as const;

export const DANCE_LINES = [
  "Work it~",
  "Watch the hips!",
  "Too hot for this desktop.",
  "Judges, take notes.",
  "Smooth. Very smooth.",
  "Yes, I know.",
  "Is it warm in here?",
  "Look at me, not your spreadsheet.",
  "Five, six, seven, eight!",
  "Lock it. Lock it!",
  "Beep boop. Boogie.",
];
